In [1]:
import numpy as np


In [2]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
#Возвращает выбранные срезы массива вдоль заданной оси.
np.compress([0, 1], a, axis=0)

array([[3, 4]])

In [5]:
np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

In [6]:
np.compress([False, True], a, axis=1)

array([[2],
       [4],
       [6]])

In [7]:
np.compress([False, True], a)

array([2])